name: Compile LSPosed Module
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Download Xposed API
        run: |
          mkdir -p app/libs
          wget https://github.com/MALTF/XposedBridgeAPI/releases/download/v82/api-82.jar -O app/libs/api-82.jar
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build APK
        run: gradle assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LuigiCameraFix-ReadyToInstall
          path: app/build/outputs/apk/debug/app-debug.apk
